"""Core module for lead enrichment pipeline."""

from core.database import Database, db, get_session, init_db, close_db
from core.models import (
    Base,
    Company,
    Contact,
    Lead,
    Campaign,
    EnrichmentLog,
    CostSummary,
    LeadStatus,
    LeadTier,
    EmailStatus,
)
from core.schemas import (
    CompanyCreate,
    CompanyEnrichment,
    CompanyResponse,
    ContactCreate,
    ContactEnrichment,
    ContactResponse,
    LeadCreate,
    LeadScoring,
    LeadResearch,
    LeadMessaging,
    LeadResponse,
    LeadDetailResponse,
    CampaignCreate,
    CampaignResponse,
    BudgetStatus,
    PipelineStatus,
)

__all__ = [
    # Database
    "Database",
    "db",
    "get_session",
    "init_db",
    "close_db",
    # Models
    "Base",
    "Company",
    "Contact",
    "Lead",
    "Campaign",
    "EnrichmentLog",
    "CostSummary",
    "LeadStatus",
    "LeadTier",
    "EmailStatus",
    # Schemas
    "CompanyCreate",
    "CompanyEnrichment",
    "CompanyResponse",
    "ContactCreate",
    "ContactEnrichment",
    "ContactResponse",
    "LeadCreate",
    "LeadScoring",
    "LeadResearch",
    "LeadMessaging",
    "LeadResponse",
    "LeadDetailResponse",
    "CampaignCreate",
    "CampaignResponse",
    "BudgetStatus",
    "PipelineStatus",
]
